services:
  shebanq:
    image: droorda/shebanq:${dockertag}
    container_name: shebanq
    hostname: shebanq
    environment:
      runmode: ${runmode}
      hostname: ${hostname}
      hostport: ${hostport}
      web2pyadminpwd: ${web2pyadminpwd}
      mysqlhost: ${mysqlhost}
      mysqlroot: ${mysqlroot}
      mysqlrootpwd: ${mysqlrootpwd}
      mysqluser: ${mysqluser}
      mysqluserpwd: ${mysqluserpwd}
      blankuserdata: ${blankuserdata}
    entrypoint: 
      - /bin/bash
      - /app/start.sh
    depends_on:
        db:
          condition: service_healthy
    volumes:
      - ./:/app
    ports:
      - "${hostport}:${hostport}"

  db:
    image: mariadb:10
    container_name: shebanqdb
    hostname: shebanqdb
    cap_add:
      - SYS_NICE
    restart: always
    healthcheck:
      test: "healthcheck.sh --connect --innodb_initialized"
      start_period: 1s
      interval: 10s
      timeout: 1s
      retries: 3
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=${mysqlrootpwd}
      - MYSQL_USER=${mysqluser}
      - MYSQL_PASSWORD=${mysqluserpwd}
    volumes:
      - "./data/mariadb:/var/lib/mysql"
      - ./src/mysql:/etc/mysql/conf.d
      - ./backup:/app/backup
